# Nome da Aplicação
spring.application.name=decifra-api

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/decifra_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Server Port da API Java
server.port=8080

gemini.api.key=AQ.Ab8RN6JXlzXsg32R82hrYsLlp6_Pu8UQ76AthJChjuwbgVb6MA

# Faz o Spring Boot não morrer imediatamente se o banco não estiver pronto
spring.datasource.continue-on-error=true
# Configurações do Hikari para tentar conectar por mais tempo
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0